device:
  device_id: "rk3588lyh"

mqtt:
  server: "10.60.83.159:1883"
  user_name: "user"
  password: "520heweijie"
  heart_topic: "rk3588lyh/info"
  heart_rate: 1000

camera:
  id: "001"
  location: "前门大院"
  rtsp_url: "rtsp://10.60.83.159:8554/rk3588lyh"
  http_url: "http://10.60.83.159:8889/rk3588lyh"
  device: "/dev/video0"
  width: 1920
  height: 1080
  fps: 25
  use_yolo: true
  detector:
    window_seconds: 8  #判定窗口的时长
    target_class_id: 0  # 目标要判断的类对应id
    frame_threshold: 20 # 判断窗口下帧的阈值
    trigger_count: 3
    model_path: "/home/cat/lyh/rk3588lyh/model/yolov8s.rknn"
    mqtt_report_topic: "rk3588lyh/001/report"
    http_report_url: "http://10.33.110.151:5002/capture/upload"
    confidence_threshold: 0.50
    nms_threshold: 0.45
    thread_num: 3
